### ISSUE TITLE
difference between Elastic search and Solr

### ISSUE THREAD

**Issue by HelloTo4x** [BigTechTalk/SparkStreaming-Kafka-ElasticSearch#1]
Hi all, do anyone know what difference between Elastic search and Solr, why do u need elastic search in this project, why don't use Solr

**Comment by BigTechTalk** [comment]
My experience with Solr is very limited, But i think this [ https://sematext.com/blog/solr-vs-elasticsearch-differences/ ] link will help you.

**Comment by HelloTo4x** [comment]
yeah, i know, @BigTechTalk can u tell me the purpose of Elastic search in your project, i really don't understand

**Comment by BigTechTalk** [comment]
Project is a part of video tutorial where i was explaining about ELK and how we can use ELK api to perform real time streaming using Apache Spark and Kafka.
